Modify trips hook
ucf-senior-design/senior-design pull request #115
Opened 2023-02-24 20:30 UTC by jaeivan

#75

2023-02-24 20:52 UTC, jaeivan commented
endpoint or functions not tested

2023-03-01 20:51 UTC, jaeivan commented
BUG: req.body is defined but req.body.title is undefined

2023-03-01 22:31 UTC, Victoria-Williamson requested changes

2023-03-01 22:31 UTC, Victoria-Williamson commented on utility/hooks/trip.tsx
> +  async function createEvent(event: Event, callback: (response: Response) => void) {
need to store event in trip useState value

2023-03-01 22:31 UTC, Victoria-Williamson commented on utility/hooks/trip.tsx
> +  async function modifyTrip(trip: Trip, callback: (response: Response) => void) {
I don't think trip needs to be passed in, since we should have access to it in this hook

2023-03-06 17:24 UTC, Victoria-Williamson requested changes

2023-03-06 17:24 UTC, Victoria-Williamson commented on pages/api/trip/[tripID]/[[...params]].ts
> +                await updateDoc(docRef, {
title isnt a value for the trip

2023-03-06 17:24 UTC, Victoria-Williamson commented on pages/api/trip/[tripID]/[[...params]].ts
> +              if (req.body.destination !== undefined) {
should also be updating duration, but both can be updated in the same updateDoc() function

2023-03-06 17:24 UTC, Victoria-Williamson commented on utility/hooks/trip.tsx
> +        joinableEvents: addEventToList(trip.joinableEvents, event),
``` Array.from(addEventToList(trip.joinableEvents, event)) ```

2023-03-06 17:24 UTC, Victoria-Williamson commented on utility/hooks/trip.tsx
> +        destination: details.destination,
need to update duration too

2023-03-06 23:55 UTC, Victoria-Williamson approved these changes

2023-03-06 23:55 UTC, merged