Hook polls
ucf-senior-design/senior-design pull request #123
Opened 2023-02-27 22:35 UTC by Nin3s

2023-02-28 06:35 UTC, Victoria-Williamson requested changes
We should be a way to tell if the user has already selected an option this way we can change the UI if it is selected such as storing the option a user voted for if there is one. Also if we do this, instead of passing the select boolean in the toggleSelect() function we can just check if the string is equal to selected. Maybe something like this can happen on mount?

Also, I may have slightly mentioned this earlier, but you may need to create a new array for setting the state to actually cause a refresh / for the update to be properly stored.

Other than that it looks really good!

2023-02-28 06:48 UTC, Victoria-Williamson requested changes

2023-02-28 06:48 UTC, Victoria-Williamson commented on utility/hooks/polls.tsx
> +    function results() {
I think instead given an option, we can calculate the percentage as long as we maybe have another variable in a useState storing the total amount of votes, this can maybe be done on mount. This is because we can get the amount of votes per option rn with poll.options[0].voters.length

2023-02-28 06:48 UTC, Victoria-Williamson commented on utility/hooks/polls.tsx
> +    function getOption(grabbedPoll: Poll): string | undefined {
see review comment in conversatino

2023-02-28 06:48 UTC, Victoria-Williamson commented on utility/hooks/polls.tsx
> +    function toggleSelect(selectedOption: string, select: boolean) {
see review comment in conversation

2023-02-28 06:48 UTC, Victoria-Williamson commented on utility/hooks/polls.tsx
> +    function didUserVote() {
see the review comment, this and ``getOption()``` logic could be merged by storing which option is selected.

2023-02-28 06:48 UTC, Victoria-Williamson commented on utility/hooks/polls.tsx
> +    function getOption(grabbedPoll: Poll): string | undefined {
also would not need to pass in grabbedPoll, bc all variables / functionality here is done per poll. Each one of these hooks would be made for each poll that we receive from the database. and we already have the data from the poll on in initialization since it is a parameter for ```usePoll(p: Poll)```

2023-02-28 06:48 UTC, Victoria-Williamson commented on utility/hooks/polls.tsx
> +            await fetch(
Sorry, I think I forgot to write the docs for this one, so the PUT for this endpoint doesn't take in a body its path is /api/trip/[tripID]/polls/[pollD]/[index] 
* where the index is the index in the array of options where the user is trying to vote. so if successful you just add the voters to this list.

2023-02-28 06:48 UTC, Victoria-Williamson commented on utility/hooks/polls.tsx
> +        newPoll: '',
what is the newPoll value for?

2023-02-28 23:16 UTC, Nin3s commented on utility/hooks/polls.tsx
> +        newPoll: '',
to be honest, I am not sure myself
I think I was using it to figure out how to store what options a user submitted

2023-02-28 23:42 UTC, Victoria-Williamson commented on utility/hooks/polls.tsx
> +        newPoll: '',
oh I see, I think this wouldn't be needed. If I remember correctly the options in the poll will just be that an not modified.

2023-03-06 22:02 UTC, Victoria-Williamson approved these changes

2023-03-06 22:08 UTC, merged