Polls connect hooks
ucf-senior-design/senior-design pull request #154
Opened 2023-03-13 16:57 UTC by Nin3s

2023-03-13 17:15 UTC, Victoria-Williamson requested changes

2023-03-13 17:15 UTC, Victoria-Williamson commented on components/Dashboard/Widgets/Poll/PollResult.tsx
> +  const { getIndex, poll } = usePoll(pollWidget)
pass in the functions from PollResult. Because when you call usePoll() here you are making a completely different poll hook than the one you are creating on line 37. So for example when you get the poll here even though it may have the same title, owner, etc. they have different references in memory because they are seperate.

2023-03-13 17:15 UTC, Victoria-Williamson commented on utility/hooks/polls.tsx
> +  function getIndex(selectedOption: string) {
not necessary, see above comments in the components. all the getIndex functions should be removed

2023-03-13 17:15 UTC, Victoria-Williamson commented on utility/hooks/polls.tsx
> +    let index = getIndex(selectedOption)
what do you need the index for here?

2023-03-13 17:15 UTC, Victoria-Williamson commented on utility/hooks/polls.tsx
> +    let index = getIndex(selectedOption)
remove getIndex and pass in index from the frontend

2023-03-13 17:15 UTC, Victoria-Williamson commented on components/Dashboard/Widgets/Poll/PollResult.tsx
>          {options.map((option, index) => {
you can get the index here, from the index in options.map((option,index))

2023-03-13 17:15 UTC, Victoria-Williamson commented on components/Dashboard/Widgets/Poll/PollResult.tsx
> +          setPercent(pollResults(getIndex(option.value)))
use index from line 43. Also, this doesn't need to be a state. This is just displaying the percentage vote for each option right? you could just return the value. Also if you use a useState here like this, all the results may have the same value I think

2023-03-13 17:15 UTC, Victoria-Williamson commented on components/Dashboard/Widgets/Poll/PollResult.tsx
> +              <OptionResults key={index} option={option} pollWidget={pollWidget} value={percent} />
make the percent (pollResults(getIndex(option.value))

2023-03-13 17:15 UTC, Victoria-Williamson commented on components/Dashboard/Widgets/Poll/PollResult.tsx
> +  const { getIndex, poll } = usePoll(pollWidget)
You should maybe consider only passing through the didUserVote function from when u create the Poll on line 37. This will allow you to tell whether the user voted or not. Then pass in the index, which you get during the map function 
https://github.com/ucf-senior-design/senior-design/blob/fc72a53fd00f936af70218d739cfe6ca96314e13/utility/hooks/polls.tsx#L79

or u can pass the string of the option the user chose

2023-03-13 17:15 UTC, Victoria-Williamson commented on components/Dashboard/Widgets/Poll/PollVote.tsx
> +                selected={getIndex(option.value) === poll.vote ? true : false}
didUserVote(option.value) could be used in the selected

2023-03-13 17:23 UTC, Nin3s commented on utility/hooks/polls.tsx
> +    let index = getIndex(selectedOption)
I think I just forgot to change it back when I realized I didn't need it

2023-03-14 10:46 UTC, Victoria-Williamson approved these changes
After these changes it should be fine!

2023-03-14 10:46 UTC, Victoria-Williamson commented on components/Dashboard/Widgets/Poll/PollVote.tsx
> +                selected={didUserVote(index) !== undefined ? true : false}
would not be undefined https://github.com/ucf-senior-design/senior-design/blob/5aa40789a12294f41188ed4bef9437ce674b375c/utility/hooks/polls.tsx#L69

you can just make it ```  selected={didUserVote(index)}```

2023-03-14 10:46 UTC, Victoria-Williamson commented on components/Dashboard/Widgets/Poll/PollResult.tsx
> +                    {pollResults(index)}%
Actually further looking at this you can actually make pollResults return what its currently returning *100 and this should be fine everywhere. So in hooks/polls.tsx

```
function pollResults(index: number) {
    return (poll.options[index].voters.length / poll.totalVotes) * 100
  }```

2023-03-14 10:46 UTC, Victoria-Williamson commented on components/Dashboard/Widgets/Poll/PollVote.tsx
> +                selectOption={selectOption}
instead of passing in index and selectOption. add parameter ```handleSelect={() => selectOption(index)}```

2023-03-14 14:34 UTC, merged