Api weather
ucf-senior-design/senior-design pull request #70
Opened 2023-02-04 06:48 UTC by Nin3s

I tried making them draggable but kept getting an error :[
weather api and ui is working otherwise tho
you can move to the /Test page to try it out

2023-02-04 06:53 UTC, Nin3s commented
jk don't do it on the deployment site I am not sure why it is not working
works locally though!!!!!!

2023-02-04 08:50 UTC, Victoria-Williamson commented on components/DashboardComponents/Weather/GetCurrentWeather.tsx
> +import { CurrentData } from '../../../utility/types/weather';
Since this function is only used in one component, you can define it there.

2023-02-04 08:50 UTC, Victoria-Williamson commented on components/DashboardComponents/Weather/GetCurrentWeather.tsx
> +  const data: CurrentData = await res.json();
slight nit but u can return await res.json() instead of storing it in a variable

2023-02-04 09:09 UTC, Victoria-Williamson requested changes
Looks good so far! Just need to move some things around

2023-02-04 09:09 UTC, Victoria-Williamson commented on pages/Test.tsx
> +// import GetCurrentWeather from '../components/DashboardComponents/Weather/GetCurrentWeather';
remove these comments

2023-02-05 06:46 UTC, Victoria-Williamson requested changes

2023-02-05 06:46 UTC, Victoria-Williamson commented on components/DashboardComponents/Weather/WeatherWidget.tsx
> +            setEditMode(true);
causes two re-renders when  you only need to do one.  could maybe make an object to hold the state with {hasError , inEditMode:}

2023-02-05 06:46 UTC, Victoria-Williamson commented on components/DashboardComponents/Weather/WeatherWidget.tsx
> +            setEditMode(false);
same here with the rerenders

2023-02-05 17:46 UTC, Nin3s commented on components/DashboardComponents/Weather/WeatherWidget.tsx
> +            setEditMode(true);
like this? 
![image](https://user-images.githubusercontent.com/50024330/216836085-c2f67fd5-0add-48a7-807c-ddbab29c62cd.png)

2023-02-05 20:18 UTC, Victoria-Williamson commented on components/DashboardComponents/Weather/WeatherWidget.tsx
> +            setEditMode(true);
yes! 💅🏾

2023-02-18 20:09 UTC, Victoria-Williamson approved these changes
Just fix the merge conflict and it should be fine

2023-02-18 20:39 UTC, merged