Complete Suggestion Widget
ucf-senior-design/senior-design pull request #97
Opened 2023-02-13 22:10 UTC by Victoria-Williamson

Resolves #73

2023-02-15 17:02 UTC, aamare1001 requested changes

2023-02-15 17:02 UTC, aamare1001 commented on utility/hooks/suggestion.tsx
> +    });
.catch?

2023-02-18 21:15 UTC, Victoria-Williamson commented on utility/hooks/suggestion.tsx
> +    });
Not needed its just checking to see what the response.status value is. So there is no error to catch

2023-02-18 21:42 UTC, aamare1001 approved these changes

2023-02-18 21:45 UTC, aamare1001 approved these changes

2023-02-18 21:46 UTC, jonathanhuydieu approved these changes

2023-02-19 17:50 UTC, merged