Team
ucf-senior-design/senior-design pull request #98
Opened 2023-02-14 00:13 UTC by jaeivan

Endpoints are done but not tested.

2023-02-14 00:16 UTC, jaeivan commented
#80 #85

2023-02-14 01:09 UTC, Victoria-Williamson commented on pages/api/teams/index.tsx
> +        res.status(200).send({});
need to return the uid for the team that you just created so it can be referenced.

2023-02-14 01:30 UTC, Victoria-Williamson commented on pages/api/teams/[teamID]/[[...params]].ts
> +    case 'DELETE': {
Should be a PUT and removes a user from the members similar to the case above

2023-02-14 01:31 UTC, Victoria-Williamson commented on pages/api/teams/index.tsx
> +    case 'POST': { // assume req.body is a valid team
not required but u could move this to the [[[...params]].ts file. also make sure to return the generated uid for this new team from firebase

2023-02-14 01:33 UTC, Victoria-Williamson commented on utility/hooks/team.tsx
> +import React from 'react';
Also I don't think teams would need its own provider maybe just a hook.

2023-02-21 02:48 UTC, Victoria-Williamson requested changes
Some of the endpoints aren't working but I set some of them up in postman to get it started.

2023-02-21 02:48 UTC, Victoria-Williamson commented on pages/api/teams/index.tsx
> +  switch (req.method) {
To make it uniform to all the other APIs can you return the entire object. So it has {uid: uid,  ....req.body}

2023-02-21 02:48 UTC, Victoria-Williamson commented on pages/api/teams/index.tsx
> +    case 'DELETE': { // asusume req.body is a valid team
I think you mentioned this one would create an error

2023-02-21 02:48 UTC, Victoria-Williamson commented on pages/api/teams/user/[userID]/[[...params]].ts
> +        let teams: string[] = new Array<string>();
You shouldn't have to pass through the users userID to get their trip b/c you can get it from firebaseAuth.currentUser. So this can go into the pages/api/teams/index.ts

2023-02-21 02:48 UTC, Victoria-Williamson commented on pages/api/teams/user/[userID]/[[...params]].ts
> +            let allTeams= await firebaseAdmin.firestore().collection('Teams/').get();
Need to query for teams that are specifically the users instead of all teams in the database

2023-02-21 02:48 UTC, Victoria-Williamson commented on pages/api/teams/[teamID]/[[...params]].ts
> +        // Returns members of a team given a team name or id
Returns status 400 when trying to get a valid team

2023-02-21 02:48 UTC, Victoria-Williamson commented on pages/api/teams/[teamID]/[[...params]].ts
> +        let userID = req.body;
need to get userID from firebaseAuth

2023-02-21 02:48 UTC, Victoria-Williamson commented on pages/api/teams/[teamID]/[[...params]].ts
> +            params.length !== 2 ||
params.length should be 1 since you are only looking for it to say 'join' or 'leave'

2023-02-21 14:26 UTC, jaeivan commented on pages/api/teams/[teamID]/[[...params]].ts
> +        let userID = req.body;
I intended for this endpoint to allow for anyone to add or remove any user from a team. If I used userID from firebaseAuth the endpoint would only be adding or removing the current user. Is it still worth changing?

2023-02-21 14:28 UTC, jaeivan commented on pages/api/teams/[teamID]/[[...params]].ts
> +        // Returns members of a team given a team name or id
What should I send instead when there is an error?

2023-02-21 17:36 UTC, Victoria-Williamson requested changes
Just a couple of small changes to help make the returned data more consistent

2023-02-21 17:36 UTC, Victoria-Williamson commented on pages/api/teams/[teamID]/[[...params]].ts
> +        // Returns members of a team given a team name or id
oh no thats fine if there is an error. The endpoint just wasn't working earlier

2023-02-21 17:36 UTC, Victoria-Williamson commented on pages/api/teams/[teamID]/[[...params]].ts
> +        let userID = req.body;
Ohh I see. That makes sense!

2023-02-21 17:36 UTC, Victoria-Williamson commented on pages/api/teams/index.tsx
> +  switch (req.method) {
Still missing

2023-02-21 17:36 UTC, Victoria-Williamson commented on pages/api/teams/user/[userID]/[[...params]].ts
> +              res.status(200).send(JSON.stringify(teams))
Make it ```send({teams:teams}})``` that way we can get the array from the JSON object.

2023-02-21 17:36 UTC, Victoria-Williamson commented on pages/api/teams/user/[userID]/[[...params]].ts
> +import { NextApiRequest, NextApiResponse } from 'next';
A nit but, this file name can be index.ts since you are not using any parameters.

so ```pages/api/teams/user/[userID]/index.ts```

2023-02-21 17:36 UTC, Victoria-Williamson commented on pages/api/teams/user/[userID]/[[...params]].ts
> +  const params = req.query.params;
remove this since its not being used

2023-02-21 17:36 UTC, Victoria-Williamson commented on utility/hooks/team.tsx
> +interface Team {
Needs to include the name of a team.

Also this should be defined globally then exported in ```types/trip.ts```

2023-02-21 17:36 UTC, Victoria-Williamson commented on pages/api/teams/[teamID]/[[...params]].ts
> +            res.status(200).send(JSON.stringify(team));
Make it send({teams:teams}}) that way we can get the array from the JSON object.

2023-02-21 23:53 UTC, Victoria-Williamson approved these changes
Add the uid to be returned when creating the team then you can merge it in

2023-02-21 23:53 UTC, Victoria-Williamson commented on pages/api/teams/index.tsx
> +  switch (req.method) {
missing the uid

2023-02-22 20:27 UTC, merged